# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import imagine_service_pb2 as imagine__service__pb2


class StableDiffusionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TextToImage = channel.unary_unary(
                '/StableDiffusionService/TextToImage',
                request_serializer=imagine__service__pb2.ImagineRequest.SerializeToString,
                response_deserializer=imagine__service__pb2.ImagineResponse.FromString,
                )


class StableDiffusionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TextToImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StableDiffusionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TextToImage': grpc.unary_unary_rpc_method_handler(
                    servicer.TextToImage,
                    request_deserializer=imagine__service__pb2.ImagineRequest.FromString,
                    response_serializer=imagine__service__pb2.ImagineResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'StableDiffusionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StableDiffusionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TextToImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StableDiffusionService/TextToImage',
            imagine__service__pb2.ImagineRequest.SerializeToString,
            imagine__service__pb2.ImagineResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
